config/routes.rb
Rails.application.routes.draw do
  resources :availibility_time_slots
  resources :appointments do
    collection do
      get 'doctor_wise_time_slots'
    end
  end
  resources :home, only: :index
  devise_for :patients, controllers: {
        sessions: 'patients/sessions',
        registrations: 'patients/registrations'
      }

  devise_scope :patient do
    authenticated  do
      root to: 'appointments#index', as: 'authenticated_patient_root'
    end

    unauthenticated do
      root to: 'home#index', as: 'unauthenticated_patient_root'
    end
  end

  devise_for :doctors, controllers: {
        sessions: 'doctors/sessions',
        registrations: 'doctors/registrations'
      }

  devise_scope :doctor do
    authenticated  do
      root to: 'appointments#index', as: 'authenticated_doctor_root'
    end

    unauthenticated do
      root to: 'home#index', as: 'unauthenticated_doctor_root'
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/availibility_time_slot.rb
class AvailibilityTimeSlot < ApplicationRecord
  ########################Associations##################################
  belongs_to :doctor
  has_many :appointments
  ########################Validations##################################
  validate :end_time_must_be_after_start_time, :end_date_must_be_after_start_date
  validates_presence_of :start_time, :end_time

  def end_time_must_be_after_start_time
    if start_time.present? && end_time.present? && start_time >= end_time
      errors.add(:end_time, "must be after start time")
    end
  end

  def end_date_must_be_after_start_date
  	if start_date > end_date
      errors.add(:end_date, "must be after start date")
    end
  end
end

app/controllers/availibility_time_slots_controller.rb
class AvailibilityTimeSlotsController < ApplicationController
  before_action :set_availibility_time_slot, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_doctor!, except: :index
  # GET /availibility_time_slots
  # GET /availibility_time_slots.json
  def index
    if current_doctor.present?
      @availibility_time_slots = current_doctor.availibility_time_slots
    else
      @availibility_time_slots = AvailibilityTimeSlot.all
    end
  end

  # GET /availibility_time_slots/1
  # GET /availibility_time_slots/1.json
  def show
  end

  # GET /availibility_time_slots/new
  def new
    @availibility_time_slot = AvailibilityTimeSlot.new
  end

  # GET /availibility_time_slots/1/edit
  def edit
  end

  # POST /availibility_time_slots
  # POST /availibility_time_slots.json
  def create
    @availibility_time_slot = AvailibilityTimeSlot.new(availibility_time_slot_params)

    respond_to do |format|
      if @availibility_time_slot.save
        format.html { redirect_to @availibility_time_slot, notice: 'Availibility time slot was successfully created.' }
        format.json { render :show, status: :created, location: @availibility_time_slot }
      else
        format.html { render :new }
        format.json { render json: @availibility_time_slot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /availibility_time_slots/1
  # PATCH/PUT /availibility_time_slots/1.json
  def update
    respond_to do |format|
      if @availibility_time_slot.update(availibility_time_slot_params)
        format.html { redirect_to @availibility_time_slot, notice: 'Availibility time slot was successfully updated.' }
        format.json { render :show, status: :ok, location: @availibility_time_slot }
      else
        format.html { render :edit }
        format.json { render json: @availibility_time_slot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /availibility_time_slots/1
  # DELETE /availibility_time_slots/1.json
  def destroy
    @availibility_time_slot.destroy
    respond_to do |format|
      format.html { redirect_to availibility_time_slots_url, notice: 'Availibility time slot was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_availibility_time_slot
      @availibility_time_slot = AvailibilityTimeSlot.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def availibility_time_slot_params
      params.require(:availibility_time_slot).permit(:start_date, :end_date, :start_time, :end_time, :doctor_id)
    end
end

app/helpers/availibility_time_slots_helper.rb
module AvailibilityTimeSlotsHelper
end

app/views/availibility_time_slots/_form.html.erb
<%= form_with(model: availibility_time_slot, local: true) do |form| %>
  <% if availibility_time_slot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(availibility_time_slot.errors.count, "error") %> prohibited this availibility_time_slot from being saved:</h2>

      <ul>
        <% availibility_time_slot.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :start_date %>
    <%= form.date_select :start_date %>
  </div>

  <div class="field">
    <%= form.label :end_date %>
    <%= form.date_select :end_date %>
  </div>

  <div class="field">
    <%= form.label :start_time %>
    <%= form.time_field :start_time, format: "%H:%M" %>
  </div>

  <div class="field">
    <%= form.label :end_time %>
    <%= form.time_field :end_time, format: "%H:%M" %>
  </div>

  <div class="field">
    <%= form.label :doctor_id %>
    <%= text_field_tag 'doctor_name', (current_doctor.name if current_doctor.present?), readonly: true %>
    <%= form.hidden_field :doctor_id, value: (current_doctor.id if current_doctor.present?) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/availibility_time_slots/edit.html.erb
<h1>Editing Availibility Time Slot</h1>

<%= render 'form', availibility_time_slot: @availibility_time_slot %>

<%= link_to 'Show', @availibility_time_slot %> |
<%= link_to 'Back', availibility_time_slots_path %>

app/views/availibility_time_slots/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Availibility Time Slots</h1>

<table>
  <thead>
    <tr>
      <th>Start date</th>
      <th>End date</th>
      <th>Start time</th>
      <th>End time</th>
      <th>Doctor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @availibility_time_slots.each do |availibility_time_slot| %>
      <tr>
        <td><%= availibility_time_slot.start_date %></td>
        <td><%= availibility_time_slot.end_date %></td>
        <td><%= availibility_time_slot.start_time.strftime("%H:%M") %></td>
        <td><%= availibility_time_slot.end_time.strftime("%H:%M") %></td>
        <td><%= availibility_time_slot.doctor.name %></td>
        <td><%= link_to 'Show', availibility_time_slot %></td>
        <% if current_doctor.present? %>
          <td><%= link_to 'Edit', edit_availibility_time_slot_path(availibility_time_slot) %></td>
          <td><%= link_to 'Destroy', availibility_time_slot, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Availibility Time Slot', new_availibility_time_slot_path if current_doctor.present? %>

app/views/availibility_time_slots/new.html.erb
<h1>New Availibility Time Slot</h1>

<%= render 'form', availibility_time_slot: @availibility_time_slot %>

<%= link_to 'Back', availibility_time_slots_path %>

app/views/availibility_time_slots/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Start date:</strong>
  <%= @availibility_time_slot.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @availibility_time_slot.start_date %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @availibility_time_slot.start_time.strftime("%H:%M") %>
</p>

<p>
  <strong>End time:</strong>
  <%= @availibility_time_slot.end_time.strftime("%H:%M") %>
</p>

<p>
  <strong>Doctor:</strong>
  <%= @availibility_time_slot.doctor.name %>
</p>

<%= link_to 'Edit', edit_availibility_time_slot_path(@availibility_time_slot) %> |
<%= link_to 'Back', availibility_time_slots_path %>