config/routes.rb
Rails.application.routes.draw do
  resources :availibility_time_slots
  resources :appointments do
    collection do
      get 'doctor_wise_time_slots'
    end
  end
  resources :home, only: :index
  devise_for :patients, controllers: {
        sessions: 'patients/sessions',
        registrations: 'patients/registrations'
      }

  devise_scope :patient do
    authenticated  do
      root to: 'appointments#index', as: 'authenticated_patient_root'
    end

    unauthenticated do
      root to: 'home#index', as: 'unauthenticated_patient_root'
    end
  end

  devise_for :doctors, controllers: {
        sessions: 'doctors/sessions',
        registrations: 'doctors/registrations'
      }

  devise_scope :doctor do
    authenticated  do
      root to: 'appointments#index', as: 'authenticated_doctor_root'
    end

    unauthenticated do
      root to: 'home#index', as: 'unauthenticated_doctor_root'
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  ########################Associations##################################
  belongs_to :patient
  belongs_to :doctor
  belongs_to :availibility_time_slot, optional: true
  ########################Validations##################################
  validate :valid_time_slot?, :check_available_time_slot, :end_time_must_be_after_start_time

  def valid_time_slot?
    unless (availibility_time_slot.start_date..availibility_time_slot.end_date).cover?(appointment_date) && start_time.between?(availibility_time_slot.start_time, availibility_time_slot.end_time) && appointment_end_time.between?(availibility_time_slot.start_time, availibility_time_slot.end_time)
      errors.add(:base, 'Your appointment date or time is not in selected availibility time slot.')
    end
  end

  def check_available_time_slot
    doctor.appointments.each do |appointment|
      if ((appointment.appointment_date == appointment_date) && (start_time.between?(appointment.start_time, appointment.appointment_end_time)) && (appointment_end_time.between?(appointment.start_time, appointment.appointment_end_time)))
        errors.add(:base, 'This appointment date and time already booked.')
        return
      end
    end
  end

  def end_time_must_be_after_start_time
    if start_time.present? && appointment_end_time.present? && start_time >= appointment_end_time
      errors.add(:appointment_end_time, "must be after start time")
    end
  end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :authenticate_patient!, only: [:new, :create]
  before_action :extra_params, only: [:new, :create]

  def index
    if current_doctor.present?
      @appointments = current_doctor.appointments
    elsif current_patient.present?
      @appointments = current_patient.appointments
    end
  end

  def new
  	@appointment = Appointment.new
  end

  def create
    @appointment = Appointment.new(appointment_params)
    respond_to do |format|
      if @appointment.save
        format.html { redirect_to appointments_path, notice: 'Appointment was successfully created.' }
        format.json { render :show, status: :created, location: @appointment }
      else
        format.html { render :new }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  def doctor_wise_time_slots
    doctor = Doctor.find_by(id: params[:doctor_id])
    if doctor.present?
      @availibility_time_slots = doctor.availibility_time_slots
    else
      @availibility_time_slots = []
    end
  end

  private

  def appointment_params
    params.require(:appointment).permit(:doctor_id, :patient_id, :description, :availibility_time_slot_id, :appointment_date, :start_time, :appointment_end_time)
  end

  def extra_params
    @doctors = Doctor.all
    @patients = Patient.all
    @availibility_time_slots = AvailibilityTimeSlot.all
  end
end

app/views/appointments/_availibility_time_slots.html.erb
<%= select_tag 'appointment[availibility_time_slot_id]', options_for_select(availibility_time_slots.map { |a| ["#{a.start_date} - #{a.end_date} #{a.start_time.strftime("%H:%M")} - #{a.end_time.strftime("%H:%M")}", a.id] }) %>

app/views/appointments/_form.html.erb
<%= form_with(model: appointment, local: true) do |form| %>
  <% if appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
        <% appointment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :doctor_id %>
    <%= form.select :doctor_id, options_for_select(@doctors.map { |d| [d.name, d.id] }), {include_blank: true } %>
  </div>

  <div class="field">
    <%= form.label :patient_id %>
    <%= form.select :patient_id, options_for_select(@patients.map { |p| [p.name, p.id] }, current_patient.id), {}, { disabled: true } %>
    <%= form.hidden_field :patient_id, value: current_patient.id %>
  </div>

  <div class="field">
    <%= form.label :availibility_time_slot_id %>
    <div class="availibility_time_slots">
      <%= render partial: 'availibility_time_slots', locals: { availibility_time_slots: @availibility_time_slots} %>
    </div>
  </div>

  <div class="field">
    <%= form.label :appointment_date %>
    <%= form.date_select :appointment_date %>
  </div>

  <div class="field">
    <%= form.label :start_time %>
    <%= form.time_field :start_time, format: "%H:%M" %>
  </div>

  <div class="field">
    <%= form.label :appointment_end_time %>
    <%= form.time_field :appointment_end_time, format: "%H:%M" %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :appointment_end_time, format: "%H:%M" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
<script type="text/javascript">
  $('#appointment_doctor_id').on('change', function(){
    $.ajax({
      url: "<%= doctor_wise_time_slots_appointments_path %>",
      type: "get",
      data: { doctor_id: $('#appointment_doctor_id').val()},
      success: function(data) {},
      error: function(data) {}
    });
  });
</script>

app/views/appointments/doctor_wise_time_slots.js.erb
$('.availibility_time_slots').html("<%= escape_javascript render(partial: 'availibility_time_slots', locals: { availibility_time_slots: @availibility_time_slots }) %>");

app/views/appointments/index.html.erb
<%= link_to 'List of available time slots', availibility_time_slots_path %>
<%= link_to 'Book Appoinment', new_appointment_path if current_patient %>
<p id="notice"><%= notice %></p>

<h1>Appointments</h1>

<table>
  <thead>
    <tr>
      <th>Doctor</th>
      <th>Patient</th>
      <th>Appoinment Date</th>
      <th>Start Time</th>
      <th>End Time</th>
      <th>Description</th>
    </tr>
  </thead>
  <tbody>
    <% @appointments.each do |appointment| %>
      <tr>
        <td><%= appointment.doctor.name %></td>
        <td><%= appointment.patient.name %></td>
        <td><%= appointment.appointment_date %></td>
        <td><%= appointment.start_time.strftime("%H:%M") if appointment.start_time %></td>
        <td><%= appointment.appointment_end_time.strftime("%H:%M") if appointment.appointment_end_time %></td>
        <td><%= appointment.description %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/appointments/new.html.erb
<h1>Book Appoinment</h1>

<%= render 'form', appointment: @appointment %>

<%= link_to 'Back', appointments_path %>